<a href="https://colab.research.google.com/github/Omkarkanemoni/Jupyter/blob/main/Main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [5]:
import pandas as pd
movies = pd.read_csv('movies.csv')

In [ ]:
print(movies.head())

      id                        title                 genre original_language  \
0    278     The Shawshank Redemption           Drama,Crime                en
1  19404  Dilwale Dulhania Le Jayenge  Comedy,Drama,Romance                hi
2    238                The Godfather           Drama,Crime                en
3    424             Schindler's List     Drama,History,War                en
4    240       The Godfather: Part II           Drama,Crime                en

                                            overview  popularity release_date  \
0  Framed in the 1940s for the double murder of h...      94.075   1994-09-23
1  Raj is a rich, carefree, happy-go-lucky second...      25.408   1995-10-19
2  Spanning the years 1945 to 1955, a chronicle o...      90.585   1972-03-14
3  The true story of how businessman Oskar Schind...      44.761   1993-12-15
4  In the continuing saga of the Corleone crime f...      57.749   1974-12-20

   vote_average  vote_count
0           8.7       21862
1           8.7        3731
2           8.7       16280
3           8.6       12959
4           8.6        9811

In [6]:
movies.describe()

                  id   popularity  vote_average    vote_count
count    2988.000000  2988.000000   2987.000000   2987.000000
mean   157049.402276    50.841985      7.525243   2438.871108
std    221330.727437   284.718222      0.336632   3934.907609
min        11.000000     0.600000      7.100000    200.000000
25%      4958.000000     9.418750      7.300000    370.000000
50%     19007.000000    14.621500      7.500000    796.000000
75%    315124.500000    31.551000      7.700000   2496.000000
max    920394.000000  8821.801000      8.700000  31917.000000

In [8]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2988 entries, 0 to 2987
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 2988 non-null   int64
 1   title              2988 non-null   object
 2   genre              2988 non-null   object
 3   original_language  2988 non-null   object
 4   overview           2988 non-null   object
 5   popularity         2988 non-null   float64
 6   release_date       2987 non-null   object
 7   vote_average       2987 non-null   float64
 8   vote_count         2987 non-null   float64
dtypes: float64(3), int64(1), object(5)
memory usage: 210.2+ KB

In [9]:
movies.isnull().sum()

id                   0
title                0
genre                0
original_language    0
overview             0
popularity           0
release_date         1
vote_average         1
vote_count           1
dtype: int64

In [10]:
movies.columns

Index(['id', 'title', 'genre', 'original_language', 'overview', 'popularity',
       'release_date', 'vote_average', 'vote_count'],
      dtype='object')

In [11]:
movies = movies[['id','title','overview','genre']]
movies

,id,title,overview,genre
0,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,"Drama,Crime"
1,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...","Comedy,Drama,Romance"
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","Drama,Crime"
3,424,Schindler's List,The true story of how businessman Oskar Schind...,"Drama,History,War"
4,240,The Godfather: Part II,In the continuing saga of the Corleone crime f...,"Drama,Crime"
...,...,...,...,...
2983,661914,One Night in Miami...,In the aftermath of Cassius Clay's defeat of S...,Drama
2984,19971,The Little Girl Who Lives Down the Lane,"Quiet, withdrawn 13-year-old Rynn Jacobs lives...","Drama,Mystery,Thriller"
2985,657,From Russia with Love,Agent 007 is back in the second installment of...,"Action,Thriller,Adventure"
2986,445,Caché,A married couple is terrorized by a series of ...,"Mystery,Drama,Thriller"
2987,399121,An Officer and a Spy,"In 1894, French Captain Alfred Dreyfus is wron...","History,Drama,Thriller"

In [12]:
movies['tags'] = movies['overview'] + movies['genre']
movies

<ipython-input-12-7769448a21d7>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'] = movies['overview'] + movies['genre']

,id,title,overview,genre,tags
0,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,"Drama,Crime",Framed in the 1940s for the double murder of h...
1,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...","Comedy,Drama,Romance","Raj is a rich, carefree, happy-go-lucky second..."
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","Drama,Crime","Spanning the years 1945 to 1955, a chronicle o..."
3,424,Schindler's List,The true story of how businessman Oskar Schind...,"Drama,History,War",The true story of how businessman Oskar Schind...
4,240,The Godfather: Part II,In the continuing saga of the Corleone crime f...,"Drama,Crime",In the continuing saga of the Corleone crime f...
...,...,...,...,...,...
2983,661914,One Night in Miami...,In the aftermath of Cassius Clay's defeat of S...,Drama,In the aftermath of Cassius Clay's defeat of S...
2984,19971,The Little Girl Who Lives Down the Lane,"Quiet, withdrawn 13-year-old Rynn Jacobs lives...","Drama,Mystery,Thriller","Quiet, withdrawn 13-year-old Rynn Jacobs lives..."
2985,657,From Russia with Love,Agent 007 is back in the second installment of...,"Action,Thriller,Adventure",Agent 007 is back in the second installment of...
2986,445,Caché,A married couple is terrorized by a series of ...,"Mystery,Drama,Thriller",A married couple is terrorized by a series of ...
2987,399121,An Officer and a Spy,"In 1894, French Captain Alfred Dreyfus is wron...","History,Drama,Thriller","In 1894, French Captain Alfred Dreyfus is wron..."

In [13]:
new_data = movies.drop(columns= ['overview','genre'])
new_data

,id,title,tags
0,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...
1,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second..."
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o..."
3,424,Schindler's List,The true story of how businessman Oskar Schind...
4,240,The Godfather: Part II,In the continuing saga of the Corleone crime f...
...,...,...,...
2983,661914,One Night in Miami...,In the aftermath of Cassius Clay's defeat of S...
2984,19971,The Little Girl Who Lives Down the Lane,"Quiet, withdrawn 13-year-old Rynn Jacobs lives..."
2985,657,From Russia with Love,Agent 007 is back in the second installment of...
2986,445,Caché,A married couple is terrorized by a series of ...
2987,399121,An Officer and a Spy,"In 1894, French Captain Alfred Dreyfus is wron..."

In [14]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
!pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.5.1-cp312-cp312-win_amd64.whl.metadata (12 kB)
Requirement already satisfied: numpy>=1.19.5 in c:\users\akshay\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (2.0.1)
Collecting scipy>=1.6.0 (from scikit-learn)
  Downloading scipy-1.14.0-cp312-cp312-win_amd64.whl.metadata (60 kB)
     ---------------------------------------- 0.0/60.8 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.8 kB ? eta -:--:--
     ------------------- ------------------ 30.7/60.8 kB 640.0 kB/s eta 0:00:01
     -------------------------------- ----- 51.2/60.8 kB 525.1 kB/s eta 0:00:01
     -------------------------------------- 60.8/60.8 kB 459.3 kB/s eta 0:00:00
Collecting joblib>=1.2.0 (from scikit-learn)
  Downloading joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn)
  Downloading threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.5.1-cp312-cp312-win_amd64.whl (10.9 MB)
   ---------------------------------------- 0.0/10.9 MB ? eta -:--:--
   ---------------------------------------- 0.1/10.9 MB 3.3 MB/s eta 0:00:04
    --------------------------------------- 0.3/10.9 MB 3.2 MB/s eta 0:00:04
   - -------------------------------------- 0.4/10.9 MB 3.2 MB/s eta 0:00:04
   -- ------------------------------------- 0.8/10.9 MB 4.5 MB/s eta 0:00:03
   ---- ----------------------------------- 1.2/10.9 MB 5.5 MB/s eta 0:00:02
   ----- ---------------------------------- 1.4/10.9 MB 5.7 MB/s eta 0:00:02
   ----- ---------------------------------- 1.4/10.9 MB 5.7 MB/s eta 0:00:02
   ------ --------------------------------- 1.7/10.9 MB 4.7 MB/s eta 0:00:02
   ------- -------------------------------- 2.0/10.9 MB 5.0 MB/s eta 0:00:02
   -------- ------------------------------- 2.3/10.9 MB 5.0 MB/s eta 0:00:02
   -------- ------------------------------- 2.3/10.9 MB 4.8 MB/s eta 0:00:02
   --------- ------------------------------ 2.5/10.9 MB 4.5 MB/s eta 0:00:02
   ---------- ----------------------------- 2.9/10.9 MB 4.9 MB/s eta 0:00:02
   ----------- ---------------------------- 3.1/10.9 MB 4.9 MB/s eta 0:00:02
   ----------- ---------------------------- 3.1/10.9 MB 4.9 MB/s eta 0:00:02
   ----------- ---------------------------- 3.3/10.9 MB 4.5 MB/s eta 0:00:02
   ------------ --------------------------- 3.5/10.9 MB 4.5 MB/s eta 0:00:02
   ------------- -------------------------- 3.8/10.9 MB 4.6 MB/s eta 0:00:02
   -------------- ------------------------- 4.0/10.9 MB 4.5 MB/s eta 0:00:02
   --------------- ------------------------ 4.2/10.9 MB 4.5 MB/s eta 0:00:02
   ---------------- ----------------------- 4.6/10.9 MB 4.7 MB/s eta 0:00:02
   ---------------- ----------------------- 4.6/10.9 MB 4.7 MB/s eta 0:00:02
   ----------------- ---------------------- 4.7/10.9 MB 4.4 MB/s eta 0:00:02
   ------------------ --------------------- 5.0/10.9 MB 4.6 MB/s eta 0:00:02
   ------------------ --------------------- 5.0/10.9 MB 4.6 MB/s eta 0:00:02
   ------------------- -------------------- 5.4/10.9 MB 4.6 MB/s eta 0:00:02
   --------------------- ------------------ 5.9/10.9 MB 4.7 MB/s eta 0:00:02
   ---------------------- ----------------- 6.2/10.9 MB 4.7 MB/s eta 0:00:02
   ----------------------- ---------------- 6.4/10.9 MB 4.7 MB/s eta 0:00:01
   ----------------------- ---------------- 6.4/10.9 MB 4.7 MB/s eta 0:00:01
   ------------------------ --------------- 6.8/10.9 MB 4.7 MB/s eta 0:00:01
   ------------------------- -------------- 6.9/10.9 MB 4.7 MB/s eta 0:00:01
   ------------------------- -------------- 7.1/10.9 MB 4.7 MB/s eta 0:00:01
   -------------------------- ------------- 7.4/10.9 MB 4.7 MB/s eta 0:00:01
   --------------------------- ------------ 7.5/10.9 MB 4.6 MB/s eta 0:00:01
   ---------------------------- ----------- 7.7/10.9 MB 4.6 MB/s eta 0:00:01
   ---------------------------- ----------- 7.8/10.9 MB 4.6 MB/s eta 0:00:01
   ----------------------------- ---------- 8.0/10.9 MB 4.6 MB/s eta 0:00:01
   ----------------------------- ---------- 8.0/10.9 MB 4.5 MB/s eta 0:00:01
   ------------------------------ --------- 8.2/10.9 MB 4.5 MB/s eta 0:00:01
   ------------------------------ --------- 8.4/10.9 MB 4.4 MB/s eta 0:00:01
   ------------------------------ --------- 8.5/10.9 MB 4.4 MB/s eta 0:00:01
   ------------------------------- -------- 8.6/10.9 MB 4.3 MB/s eta 0:00:01
   ------------------------------- -------- 8.7/10.9 MB 4.3 MB/s eta 0:00:01
   -------------------------------- ------- 8.8/10.9 MB 4.2 MB/s eta 0:00:01
   -------------------------------- ------- 8.9/10.9 MB 4.2 MB/s eta 0:00:01
   --------------------------------- ------ 9.0/10.9 MB 4.2 MB/s eta 0:00:01
   --------------------------------- ------ 9.2/10.9 MB 4.1 MB/s eta 0:00:01
   --------------------------------- ------ 9.3/10.9 MB 4.1 MB/s eta 0:00:01
   ---------------------------------- ----- 9.4/10.9 MB 4.0 MB/s eta 0:00:01
   ---------------------------------- ----- 9.5/10.9 MB 4.0 MB/s eta 0:00:01
   ----------------------------------- ---- 9.6/10.9 MB 4.0 MB/s eta 0:00:01
   ----------------------------------- ---- 9.7/10.9 MB 4.0 MB/s eta 0:00:01
   ------------------------------------ --- 9.9/10.9 MB 3.9 MB/s eta 0:00:01
   ------------------------------------ --- 10.0/10.9 MB 3.9 MB/s eta 0:00:01
   ------------------------------------ --- 10.1/10.9 MB 3.9 MB/s eta 0:00:01
   ------------------------------------ --- 10.1/10.9 MB 3.9 MB/s eta 0:00:01
   ------------------------------------ --- 10.1/10.9 MB 3.9 MB/s eta 0:00:01
   ------------------------------------- -- 10.2/10.9 MB 3.7 MB/s eta 0:00:01
   ------------------------------------- -- 10.2/10.9 MB 3.7 MB/s eta 0:00:01
   ------------------------------------- -- 10.3/10.9 MB 3.6 MB/s eta 0:00:01
   ------------------------------------- -- 10.4/10.9 MB 3.6 MB/s eta 0:00:01
   ------------------------------------- -- 10.4/10.9 MB 3.6 MB/s eta 0:00:01
   ------------------------------------- -- 10.4/10.9 MB 3.6 MB/s eta 0:00:01
   -------------------------------------- - 10.5/10.9 MB 3.5 MB/s eta 0:00:01
   -------------------------------------- - 10.5/10.9 MB 3.5 MB/s eta 0:00:01
   -------------------------------------- - 10.6/10.9 MB 3.4 MB/s eta 0:00:01
   -------------------------------------- - 10.7/10.9 MB 3.4 MB/s eta 0:00:01
   -------------------------------------- - 10.7/10.9 MB 3.4 MB/s eta 0:00:01
   -------------------------------------- - 10.7/10.9 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------  10.8/10.9 MB 3.3 MB/s eta 0:00:01
   ---------------------------------------  10.8/10.9 MB 3.2 MB/s eta 0:00:01
   ---------------------------------------  10.9/10.9 MB 3.2 MB/s eta 0:00:01
   ---------------------------------------  10.9/10.9 MB 3.2 MB/s eta 0:00:01
   ---------------------------------------- 10.9/10.9 MB 3.1 MB/s eta 0:00:00
Downloading joblib-1.4.2-py3-none-any.whl (301 kB)
   ---------------------------------------- 0.0/301.8 kB ? eta -:--:--
   ---------------- ----------------------- 122.9/301.8 kB 3.6 MB/s eta 0:00:01
   -------------------------------- ------- 245.8/301.8 kB 3.0 MB/s eta 0:00:01
   ---------------------------------------- 301.8/301.8 kB 2.3 MB/s eta 0:00:00
Downloading scipy-1.14.0-cp312-cp312-win_amd64.whl (44.5 MB)
   ---------------------------------------- 0.0/44.5 MB ? eta -:--:--
   ---------------------------------------- 0.1/44.5 MB 3.2 MB/s eta 0:00:14
   ---------------------------------------- 0.2/44.5 MB 3.0 MB/s eta 0:00:15
   ---------------------------------------- 0.3/44.5 MB 2.9 MB/s eta 0:00:16
   ---------------------------------------- 0.3/44.5 MB 2.9 MB/s eta 0:00:16
   ---------------------------------------- 0.3/44.5 MB 2.9 MB/s eta 0:00:16
   ---------------------------------------- 0.4/44.5 MB 1.5 MB/s eta 0:00:30
   ---------------------------------------- 0.4/44.5 MB 1.3 MB/s eta 0:00:33
   ---------------------------------------- 0.5/44.5 MB 1.4 MB/s eta 0:00:32
   ---------------------------------------- 0.5/44.5 MB 1.4 MB/s eta 0:00:31
   ---------------------------------------- 0.5/44.5 MB 1.4 MB/s eta 0:00:31
   ---------------------------------------- 0.5/44.5 MB 1.4 MB/s eta 0:00:31
    --------------------------------------- 0.7/44.5 MB 1.3 MB/s eta 0:00:35
    --------------------------------------- 0.7/44.5 MB 1.2 MB/s eta 0:00:37
    --------------------------------------- 0.8/44.5 MB 1.2 MB/s eta 0:00:37
    --------------------------------------- 0.8/44.5 MB 1.2 MB/s eta 0:00:37
    --------------------------------------- 0.8/44.5 MB 1.2 MB/s eta 0:00:37
    --------------------------------------- 0.9/44.5 MB 1.2 MB/s eta 0:00:36
    --------------------------------------- 1.0/44.5 MB 1.2 MB/s eta 0:00:38
    --------------------------------------- 1.0/44.5 MB 1.2 MB/s eta 0:00:37
    --------------------------------------- 1.0/44.5 MB 1.2 MB/s eta 0:00:37
    --------------------------------------- 1.0/44.5 MB 1.1 MB/s eta 0:00:42
    --------------------------------------- 1.1/44.5 MB 1.1 MB/s eta 0:00:40
   - -------------------------------------- 1.1/44.5 MB 1.1 MB/s eta 0:00:41
   - -------------------------------------- 1.2/44.5 MB 1.1 MB/s eta 0:00:40
   - -------------------------------------- 1.2/44.5 MB 1.1 MB/s eta 0:00:40
   - -------------------------------------- 1.2/44.5 MB 1.1 MB/s eta 0:00:40
   - -------------------------------------- 1.3/44.5 MB 1.1 MB/s eta 0:00:41
   - -------------------------------------- 1.4/44.5 MB 1.1 MB/s eta 0:00:41
   - -------------------------------------- 1.4/44.5 MB 1.0 MB/s eta 0:00:42
   - -------------------------------------- 1.5/44.5 MB 1.1 MB/s eta 0:00:40
   - -------------------------------------- 1.5/44.5 MB 1.1 MB/s eta 0:00:40
   - -------------------------------------- 1.5/44.5 MB 1.1 MB/s eta 0:00:40
   - -------------------------------------- 1.6/44.5 MB 1.1 MB/s eta 0:00:41
   - -------------------------------------- 1.6/44.5 MB 1.0 MB/s eta 0:00:42
   - -------------------------------------- 1.7/44.5 MB 1.1 MB/s eta 0:00:41
   - -------------------------------------- 1.8/44.5 MB 1.1 MB/s eta 0:00:40
   - -------------------------------------- 1.8/44.5 MB 1.1 MB/s eta 0:00:40
   - -------------------------------------- 1.8/44.5 MB 1.1 MB/s eta 0:00:40
   - -------------------------------------- 1.9/44.5 MB 1.0 MB/s eta 0:00:41
   - -------------------------------------- 1.9/44.5 MB 1.0 MB/s eta 0:00:41
   - -------------------------------------- 2.0/44.5 MB 1.1 MB/s eta 0:00:41
   - -------------------------------------- 2.1/44.5 MB 1.1 MB/s eta 0:00:39
   -- ------------------------------------- 2.3/44.5 MB 1.1 MB/s eta 0:00:38
   -- ------------------------------------- 2.4/44.5 MB 1.2 MB/s eta 0:00:37
   -- ------------------------------------- 2.5/44.5 MB 1.2 MB/s eta 0:00:36
   -- ------------------------------------- 2.6/44.5 MB 1.2 MB/s eta 0:00:35
   -- ------------------------------------- 2.8/44.5 MB 1.3 MB/s eta 0:00:34
   -- ------------------------------------- 2.9/44.5 MB 1.3 MB/s eta 0:00:33
   -- ------------------------------------- 3.0/44.5 MB 1.3 MB/s eta 0:00:32
   -- ------------------------------------- 3.1/44.5 MB 1.3 MB/s eta 0:00:31
   -- ------------------------------------- 3.3/44.5 MB 1.4 MB/s eta 0:00:30
   --- ------------------------------------ 3.4/44.5 MB 1.4 MB/s eta 0:00:30
   --- ------------------------------------ 3.5/44.5 MB 1.4 MB/s eta 0:00:29
   --- ------------------------------------ 3.6/44.5 MB 1.5 MB/s eta 0:00:29
   --- ------------------------------------ 3.8/44.5 MB 1.5 MB/s eta 0:00:28
   --- ------------------------------------ 3.9/44.5 MB 1.5 MB/s eta 0:00:28
   --- ------------------------------------ 4.0/44.5 MB 1.5 MB/s eta 0:00:27
   --- ------------------------------------ 4.1/44.5 MB 1.5 MB/s eta 0:00:27
   --- ------------------------------------ 4.3/44.5 MB 1.6 MB/s eta 0:00:26
   --- ------------------------------------ 4.4/44.5 MB 1.6 MB/s eta 0:00:26
   ---- ----------------------------------- 4.5/44.5 MB 1.6 MB/s eta 0:00:26
   ---- ----------------------------------- 4.7/44.5 MB 1.6 MB/s eta 0:00:25
   ---- ----------------------------------- 4.8/44.5 MB 1.6 MB/s eta 0:00:25
   ---- ----------------------------------- 4.9/44.5 MB 1.7 MB/s eta 0:00:24
   ---- ----------------------------------- 5.1/44.5 MB 1.7 MB/s eta 0:00:24
   ---- ----------------------------------- 5.2/44.5 MB 1.7 MB/s eta 0:00:24
   ---- ----------------------------------- 5.3/44.5 MB 1.7 MB/s eta 0:00:23
   ---- ----------------------------------- 5.5/44.5 MB 1.7 MB/s eta 0:00:23
   ----- ---------------------------------- 5.6/44.5 MB 1.7 MB/s eta 0:00:23
   ----- ---------------------------------- 5.7/44.5 MB 1.7 MB/s eta 0:00:23
   ----- ---------------------------------- 5.9/44.5 MB 1.8 MB/s eta 0:00:22
   ----- ---------------------------------- 6.0/44.5 MB 1.8 MB/s eta 0:00:22
   ----- ---------------------------------- 6.1/44.5 MB 1.8 MB/s eta 0:00:22
   ----- ---------------------------------- 6.3/44.5 MB 1.8 MB/s eta 0:00:22
   ----- ---------------------------------- 6.4/44.5 MB 1.8 MB/s eta 0:00:21
   ----- ---------------------------------- 6.6/44.5 MB 1.9 MB/s eta 0:00:21
   ----- ---------------------------------- 6.7/44.5 MB 1.9 MB/s eta 0:00:21
   ------ --------------------------------- 6.8/44.5 MB 1.9 MB/s eta 0:00:21
   ------ --------------------------------- 6.9/44.5 MB 1.9 MB/s eta 0:00:20
   ------ --------------------------------- 7.1/44.5 MB 1.9 MB/s eta 0:00:20
   ------ --------------------------------- 7.2/44.5 MB 1.9 MB/s eta 0:00:20
   ------ --------------------------------- 7.4/44.5 MB 1.9 MB/s eta 0:00:20
   ------ --------------------------------- 7.5/44.5 MB 1.9 MB/s eta 0:00:20
   ------ --------------------------------- 7.6/44.5 MB 1.9 MB/s eta 0:00:19
   ------ --------------------------------- 7.7/44.5 MB 2.0 MB/s eta 0:00:19
   ------- -------------------------------- 7.9/44.5 MB 2.0 MB/s eta 0:00:19
   ------- -------------------------------- 8.0/44.5 MB 2.0 MB/s eta 0:00:19
   ------- -------------------------------- 8.2/44.5 MB 2.0 MB/s eta 0:00:19
   ------- -------------------------------- 8.3/44.5 MB 2.0 MB/s eta 0:00:19
   ------- -------------------------------- 8.4/44.5 MB 2.0 MB/s eta 0:00:18
   ------- -------------------------------- 8.6/44.5 MB 2.0 MB/s eta 0:00:18
   ------- -------------------------------- 8.7/44.5 MB 2.0 MB/s eta 0:00:18
   ------- -------------------------------- 8.8/44.5 MB 2.0 MB/s eta 0:00:18
   -------- ------------------------------- 9.0/44.5 MB 2.1 MB/s eta 0:00:18
   -------- ------------------------------- 9.1/44.5 MB 2.1 MB/s eta 0:00:18
   -------- ------------------------------- 9.3/44.5 MB 2.1 MB/s eta 0:00:17
   -------- ------------------------------- 9.4/44.5 MB 2.1 MB/s eta 0:00:17
   -------- ------------------------------- 9.6/44.5 MB 2.1 MB/s eta 0:00:17
   -------- ------------------------------- 9.7/44.5 MB 2.1 MB/s eta 0:00:17
   -------- ------------------------------- 9.9/44.5 MB 2.1 MB/s eta 0:00:17
   --------- ------------------------------ 10.0/44.5 MB 2.1 MB/s eta 0:00:17
   --------- ------------------------------ 10.2/44.5 MB 2.1 MB/s eta 0:00:17
   --------- ------------------------------ 10.3/44.5 MB 2.1 MB/s eta 0:00:16
   --------- ------------------------------ 10.5/44.5 MB 2.2 MB/s eta 0:00:16
   --------- ------------------------------ 10.6/44.5 MB 2.2 MB/s eta 0:00:16
   --------- ------------------------------ 10.8/44.5 MB 2.3 MB/s eta 0:00:15
   --------- ------------------------------ 11.0/44.5 MB 2.3 MB/s eta 0:00:15
   ---------- ----------------------------- 11.1/44.5 MB 2.4 MB/s eta 0:00:14
   ---------- ----------------------------- 11.3/44.5 MB 2.5 MB/s eta 0:00:14
   ---------- ----------------------------- 11.4/44.5 MB 2.5 MB/s eta 0:00:14
   ---------- ----------------------------- 11.6/44.5 MB 2.6 MB/s eta 0:00:13
   ---------- ----------------------------- 11.7/44.5 MB 2.8 MB/s eta 0:00:12
   ---------- ----------------------------- 11.9/44.5 MB 2.8 MB/s eta 0:00:12
   ---------- ----------------------------- 12.0/44.5 MB 2.9 MB/s eta 0:00:12
   ---------- ----------------------------- 12.1/44.5 MB 2.9 MB/s eta 0:00:12
   ----------- ---------------------------- 12.2/44.5 MB 2.9 MB/s eta 0:00:11
   ----------- ---------------------------- 12.5/44.5 MB 3.0 MB/s eta 0:00:11
   ----------- ---------------------------- 12.5/44.5 MB 3.0 MB/s eta 0:00:11
   ----------- ---------------------------- 12.6/44.5 MB 2.9 MB/s eta 0:00:11
   ----------- ---------------------------- 12.7/44.5 MB 2.9 MB/s eta 0:00:11
   ----------- ---------------------------- 12.8/44.5 MB 2.9 MB/s eta 0:00:11
   ----------- ---------------------------- 12.9/44.5 MB 2.9 MB/s eta 0:00:11
   ----------- ---------------------------- 13.0/44.5 MB 2.9 MB/s eta 0:00:11
   ----------- ---------------------------- 13.0/44.5 MB 2.9 MB/s eta 0:00:11
   ----------- ---------------------------- 13.1/44.5 MB 2.9 MB/s eta 0:00:11
   ----------- ---------------------------- 13.2/44.5 MB 2.8 MB/s eta 0:00:11
   ----------- ---------------------------- 13.3/44.5 MB 2.8 MB/s eta 0:00:12
   ------------ --------------------------- 13.4/44.5 MB 2.8 MB/s eta 0:00:12
   ------------ --------------------------- 13.4/44.5 MB 2.8 MB/s eta 0:00:12
   ------------ --------------------------- 13.5/44.5 MB 2.8 MB/s eta 0:00:12
   ------------ --------------------------- 13.6/44.5 MB 2.8 MB/s eta 0:00:12
   ------------ --------------------------- 13.7/44.5 MB 2.8 MB/s eta 0:00:12
   ------------ --------------------------- 13.8/44.5 MB 2.8 MB/s eta 0:00:12
   ------------ --------------------------- 13.9/44.5 MB 2.8 MB/s eta 0:00:12
   ------------ --------------------------- 14.0/44.5 MB 2.7 MB/s eta 0:00:12
   ------------ --------------------------- 14.1/44.5 MB 2.7 MB/s eta 0:00:12
   ------------ --------------------------- 14.2/44.5 MB 2.7 MB/s eta 0:00:12
   ------------ --------------------------- 14.3/44.5 MB 2.7 MB/s eta 0:00:12
   ------------ --------------------------- 14.4/44.5 MB 2.7 MB/s eta 0:00:12
   ------------ --------------------------- 14.4/44.5 MB 2.7 MB/s eta 0:00:12
   ------------- -------------------------- 14.5/44.5 MB 2.7 MB/s eta 0:00:12
   ------------- -------------------------- 14.7/44.5 MB 2.7 MB/s eta 0:00:12
   ------------- -------------------------- 14.7/44.5 MB 2.7 MB/s eta 0:00:12
   ------------- -------------------------- 14.8/44.5 MB 2.7 MB/s eta 0:00:12
   ------------- -------------------------- 15.0/44.5 MB 2.7 MB/s eta 0:00:12
   ------------- -------------------------- 15.1/44.5 MB 2.7 MB/s eta 0:00:12
   ------------- -------------------------- 15.2/44.5 MB 2.7 MB/s eta 0:00:12
   ------------- -------------------------- 15.3/44.5 MB 2.6 MB/s eta 0:00:12
   ------------- -------------------------- 15.4/44.5 MB 2.6 MB/s eta 0:00:12
   ------------- -------------------------- 15.5/44.5 MB 2.6 MB/s eta 0:00:12
   -------------- ------------------------- 15.6/44.5 MB 2.6 MB/s eta 0:00:12
   -------------- ------------------------- 15.7/44.5 MB 2.6 MB/s eta 0:00:12
   -------------- ------------------------- 15.7/44.5 MB 2.6 MB/s eta 0:00:12
   -------------- ------------------------- 15.9/44.5 MB 2.6 MB/s eta 0:00:12
   -------------- ------------------------- 16.0/44.5 MB 2.6 MB/s eta 0:00:12
   -------------- ------------------------- 16.0/44.5 MB 2.6 MB/s eta 0:00:12
   -------------- ------------------------- 16.1/44.5 MB 2.6 MB/s eta 0:00:12
   -------------- ------------------------- 16.2/44.5 MB 2.5 MB/s eta 0:00:12
   -------------- ------------------------- 16.3/44.5 MB 2.5 MB/s eta 0:00:12
   -------------- ------------------------- 16.3/44.5 MB 2.5 MB/s eta 0:00:12
   -------------- ------------------------- 16.4/44.5 MB 2.5 MB/s eta 0:00:12
   -------------- ------------------------- 16.5/44.5 MB 2.5 MB/s eta 0:00:12

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [15]:
from sklearn.feature_extraction.text import CountVectorizer

In [16]:
cv = CountVectorizer(max_features=10000, stop_words='english')

In [17]:
cv

CountVectorizer(max_features=10000, stop_words='english')

In [18]:
vector= cv.fit_transform(new_data['tags'].values.astype('U')).toarray()

In [19]:
vector.shape

(2988, 10000)

In [20]:
from sklearn.metrics.pairwise import cosine_similarity

In [21]:
similarity=cosine_similarity(vector)

In [22]:
similarity

array([[1.        , 0.04652421, 0.1176552 , ..., 0.04279605, 0.048795  ,
        0.07968191],
       [0.04652421, 1.        , 0.06897007, ..., 0.02090605, 0.09534626,
        0.03892495],
       [0.1176552 , 0.06897007, 1.        , ..., 0.08459099, 0.04822428,
        0.07874992],
       ...,
       [0.04279605, 0.02090605, 0.08459099, ..., 1.        , 0.1315587 ,
        0.07161149],
       [0.048795  , 0.09534626, 0.04822428, ..., 0.1315587 , 1.        ,
        0.16329932],
       [0.07968191, 0.03892495, 0.07874992, ..., 0.07161149, 0.16329932,
        1.        ]])

In [23]:
new_data[new_data['title']=="The Godfather"].index[0]

2

In [24]:
distance = sorted(list(enumerate(similarity[2])), reverse=True, key=lambda vector:vector[1])
for i in distance[0:5]:
    print(new_data.iloc[i[0]].title)

The Godfather
The Godfather: Part II
Joker
Bomb City
Felon

In [25]:
def recommand(movies):
    index=new_data[new_data['title']==movies].index[0]
    distance = sorted(list(enumerate(similarity[index])), reverse=True, key=lambda vector:vector[1])
    for i in distance[0:5]:
        print(new_data.iloc[i[0]].title)

In [26]:
recommand("Iron Man")

Iron Man
Avengers: Age of Ultron
Guardians of the Galaxy Vol. 2
Star Wars: Episode III - Revenge of the Sith
G.O.R.A.

In [27]:
import pickle

In [28]:
pickle.dump(new_data, open('movies_list.pkl', 'wb'))

In [29]:
pickle.dump(similarity, open('similarity.pkl', 'wb'))

In [30]:
pickle.load(open('movies_list.pkl', 'rb'))

,id,title,tags
0,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...
1,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second..."
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o..."
3,424,Schindler's List,The true story of how businessman Oskar Schind...
4,240,The Godfather: Part II,In the continuing saga of the Corleone crime f...
...,...,...,...
2983,661914,One Night in Miami...,In the aftermath of Cassius Clay's defeat of S...
2984,19971,The Little Girl Who Lives Down the Lane,"Quiet, withdrawn 13-year-old Rynn Jacobs lives..."
2985,657,From Russia with Love,Agent 007 is back in the second installment of...
2986,445,Caché,A married couple is terrorized by a series of ...
2987,399121,An Officer and a Spy,"In 1894, French Captain Alfred Dreyfus is wron..."

In [35]:
recommand("The Godfather: Part II")

The Godfather: Part II
The Godfather
The Godfather: Part III
Barton Fink
Brooklyn

In [ ]:
from google.colab import drive
drive.mount('/content/drive')